theme: minima
title: Serkan Sevilgen
minima:
  social_links:
    soundcloud: serkansevilgen
    github: serkansevilgen
    facebook: sserkansevilgen
    instagram: serkansevilgen
    linkedin: serkansevilgen

header_pages:
  - readme.md
  - music.md
  - events.nd