theme: minima
title: Serkan Sevilgen
description: Serkan Sevilgen computer programmer and composer
minima:
  social_links:
    instagram: serkansevilgen
    linkedin: serkansevilgen
    facebook: aserkansevilgen
header_pages:
  - readme.md
  - music.md
  - events.nd